name: Release
on:
  push: { tags: v[0-9]+.* }
  workflow_dispatch:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - run: bundle exec rake build
      - run: gem push pkg/*.gem
        env:
          GEM_HOST_API_KEY: Bearer ${{github.token}}
          RUBYGEMS_HOST: https://rubygems.pkg.github.com/${{github.repository_owner}}
